### ISSUE TITLE
[1.12] Bug with Mod "Streams"

### ISSUE THREAD

**Issue by MasterEnderman** [asiekierka/SmoothWaterMC#2]
It's me.... again!
If you are using this mod together with Streams (https://minecraft.curseforge.com/projects/streams) all blocks from Streams show the missing texture block. It works fine if you remove SmoothWater.

Smooth Water: 0.1.2
Streams: 0.4.2
Forge: 14.23.1.2606
Foamfix: 0.9.1-anarchy

**Comment by asiekierka** [comment]
Incorrect; only Rivers from Farseek suffer from this issue.

**Comment by asiekierka** [comment]
Fixed in 0.1.3
