### ISSUE TITLE
Massive FPS drop when using Frost Walker enchantment or similar effects.

### ISSUE THREAD

**Issue by Scorch-Mechanic** [asiekierka/SmoothWaterMC#3]
Apparently rapidly generating and melting transparent blocks on top of oceans will generate scores upon scores of lighting updates on the ocean floor, causing massive FPS drop! Who woulda thunkit?

I realize it's probably unfixable, which is a goddamn shame because this is a seriously nice mod. Similar results can be obtained with Botania's Snowflake Pendant (which apparently just calls mojang's frost walker code, but in a wider area) and Reliquary's Glacial Staff (the effect of which actually predates frost walker's addition to minecraft).
[modlist.txt](https://github.com/asiekierka/SmoothWaterMC/files/1760231/modlist.txt)

**Comment by asiekierka** [comment]
Enable alwaysSetupTerrainOffThread in forge.cfg.

**Comment by Scorch-Mechanic** [comment]
Hot damn, that's a massive improvement. The ice blocks render a little strangely as per the warning in the file, but it works! 

Learn somethin' new every day. Thankyew kindly.
